export const dashboardPage = `<!doctype html>
<html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BusBot · Análisis de rutas</title>
<style>
  :root { color-scheme: dark; --bg:#09121f; --panel:#101f32; --line:#25415d; --ink:#e9f2fb; --muted:#9db0c5; --accent:#46d7b0; --warn:#ffc857; --bad:#ff7b7b; --blue:#79a9ff; }
  * { box-sizing:border-box } body { margin:0; font:15px system-ui,sans-serif; background:radial-gradient(ellipse at 15% -10%,#18314a 0,transparent 42%),var(--bg); color:var(--ink) }
  main { max-width:1540px; margin:auto; padding:28px } header { display:flex; justify-content:space-between; gap:20px; align-items:center; flex-wrap:wrap }
  h1 { margin:0; font-size:1.8rem; letter-spacing:-.03em } h2 { margin:0 0 12px; font-size:1.05rem } p { line-height:1.5 } .muted { color:var(--muted) }
  nav { display:flex; flex-wrap:wrap; gap:8px; margin:22px 0 4px } nav a { color:var(--muted); text-decoration:none; border:1px solid var(--line); border-radius:20px; padding:7px 12px } nav a:hover { color:var(--ink); border-color:var(--accent) }
  #stats { display:grid; grid-template-columns:repeat(auto-fit,minmax(155px,1fr)); gap:12px; margin:18px 0 }
  .stat,section,.chart-card { background:linear-gradient(145deg,rgba(20,39,60,.98),rgba(14,29,46,.98)); border:1px solid var(--line); border-radius:14px; padding:17px; box-shadow:0 10px 28px rgba(0,0,0,.12) }
  .stat span { color:var(--muted); font-size:.85rem } .stat b { display:block; font-size:1.65rem; margin-top:5px; letter-spacing:-.04em }
  section { margin-top:16px; scroll-margin-top:16px } .section-head { display:flex; justify-content:space-between; gap:14px; align-items:start; flex-wrap:wrap; margin-bottom:12px }
  table { width:100%; border-collapse:collapse; white-space:nowrap } th,td { text-align:left; vertical-align:top; padding:10px 9px; border-bottom:1px solid rgba(65,94,123,.55) } th { color:var(--muted); font-size:.8rem; font-weight:650; letter-spacing:.02em } tbody tr:hover { background:rgba(121,169,255,.045) }
  .table-wrap { overflow:auto; max-height:580px } .available,.sent,.checked { color:var(--accent) } .full_or_unavailable,.failed { color:var(--bad) } .schedule_only,.pending { color:var(--warn) } .error { color:var(--bad) }
  .controls { display:flex; flex-wrap:wrap; gap:10px; margin:10px 0 12px } input,select { background:#0b1726; color:var(--ink); border:1px solid var(--line); border-radius:9px; padding:9px 10px; font:inherit } input { min-width:230px; flex:1 }
  .download-button { display:inline-flex; align-items:center; gap:8px; border:1px solid var(--accent); border-radius:9px; padding:10px 13px; color:var(--accent); text-decoration:none; font-weight:650; white-space:nowrap } .download-button:hover { background:#12332f }
  .charts { display:grid; grid-template-columns:1.35fr 1fr; gap:14px; margin:14px 0 } .chart-card { min-width:0 } canvas { width:100%; height:245px; display:block } .chart-legend { display:flex; flex-wrap:wrap; gap:8px 16px; margin-top:6px; color:var(--muted); font-size:.82rem } .legend-item { display:inline-flex; align-items:center; gap:6px } .swatch { width:9px;height:9px;border-radius:3px;display:inline-block }
  .tweet-link { color:var(--accent); text-decoration:none; font-weight:600 } .tweet-link:hover { text-decoration:underline } .message-cell { white-space:normal; min-width:280px; max-width:680px; line-height:1.45 }
  .badge { display:inline-block; border:1px solid currentColor; border-radius:999px; padding:2px 8px; font-size:.78rem }
  #load-error { color:var(--bad); margin:12px 0; display:none }
  @media(max-width:850px){main{padding:20px}.charts{grid-template-columns:1fr}}
  @media(max-width:600px){main{padding:14px}h1{font-size:1.45rem}table{font-size:.82rem}th,td{padding:8px 6px}.message-cell{min-width:230px}}
</style>
<main>
  <header><div><h1>BusBot · Análisis de rutas</h1><div class="muted" id="updated">Cargando datos…</div></div><a class="download-button" href="/api/database.sqlite" download>⇩ Descargar base de datos</a></header>
  <nav aria-label="Secciones del panel"><a href="#overview">Resumen</a><a href="#planned">Rutas</a><a href="#history">Historial</a><a href="#tweets">Tweets enviados</a><a href="#rail">Renfe</a></nav>
  <div id="load-error" role="status"></div><div id="stats" aria-live="polite"></div>
  <div id="overview" class="charts">
    <div class="chart-card"><h2>Ocupación media · últimos 14 días</h2><div class="muted">Porcentaje medio de plazas ocupadas.</div><canvas id="occupancy-chart" aria-label="Ocupación media por día"></canvas></div>
    <div class="chart-card"><h2>Estado de expediciones de hoy</h2><div class="muted">Distribución de las rutas observadas hoy.</div><canvas id="status-chart" aria-label="Estados de expediciones"></canvas><div id="status-legend" class="chart-legend"></div></div>
    <div class="chart-card"><h2>Actividad del bot · últimos 14 días</h2><div class="muted">Tweets únicos enviados por fecha.</div><canvas id="tweets-chart" aria-label="Tweets enviados por día"></canvas></div>
  </div>
  <section><div class="section-head"><div><h2>Próximas comprobaciones</h2><div class="muted">El recolector consulta las salidas alrededor de T−10 minutos.</div></div></div><div class="table-wrap"><table><thead><tr><th>Operador</th><th>Ruta</th><th>Salida</th><th>Pull previsto</th><th>Estado</th></tr></thead><tbody id="upcoming"></tbody></table></div></section>
  <section id="planned"><div class="section-head"><div><h2>Rutas planificadas</h2><div class="muted">Busca por operador, origen o destino.</div></div><div class="muted" id="route-total"></div></div><div class="controls"><input id="route-search" type="search" placeholder="Buscar rutas…"><select id="operator-filter"><option value="">Todos los operadores</option></select></div><div class="table-wrap"><table><thead><tr><th>Operador</th><th>Origen</th><th>Destino</th></tr></thead><tbody id="planned-routes"></tbody></table></div></section>
  <section id="history"><div class="section-head"><div><h2>Historial de ocupación</h2><div class="muted" id="history-range"></div></div><div class="muted" id="history-total"></div></div><div class="controls"><input id="history-search" type="search" placeholder="Filtrar por operador o ruta…"><select id="history-status"><option value="">Todos los estados</option><option value="available">Con plazas</option><option value="full_or_unavailable">Lleno / sin disponibilidad</option><option value="schedule_only">Solo horario</option><option value="error">Error de consulta</option></select></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Operador</th><th>Ruta</th><th>Salida</th><th>Ocupación</th><th>Precio</th><th>Estado</th><th>Actualizada</th></tr></thead><tbody id="history-rows"></tbody></table></div></section>
  <section id="tweets"><div class="section-head"><div><h2>Tweets enviados</h2><div class="muted">Un enlace por publicación; varios avisos pueden compartir el mismo tweet.</div></div><div class="muted" id="tweet-total"></div></div><div class="table-wrap"><table><thead><tr><th>Publicado</th><th>Eventos</th><th>Avisos incluidos</th><th>Enlace al tweet</th></tr></thead><tbody id="sent-tweets"></tbody></table></div></section>
  <section><h2>Cola e incidencias de publicación</h2><div class="muted">Avisos pendientes y errores para facilitar el diagnóstico.</div><div class="table-wrap"><table><thead><tr><th>Detectada</th><th>Tipo</th><th>Mensaje</th><th>Estado</th><th>Detalle</th></tr></thead><tbody id="x-posts"></tbody></table></div></section>
  <section id="rail"><div class="section-head"><div><h2>Trenes Renfe observados</h2><div class="muted">Último inventario del feed oficial.</div></div><div class="muted" id="renfe-total"></div></div><div class="table-wrap"><table><thead><tr><th>Tren</th><th>Circulación</th><th>Trayecto</th><th>Próxima estación</th><th>Llegada estimada</th><th>Retraso</th><th>Visto</th></tr></thead><tbody id="renfe-trains"></tbody></table></div></section>
  <section><h2>Avisos de llegadas nocturnas Renfe</h2><div class="table-wrap"><table><thead><tr><th>Registrada</th><th>Tren</th><th>Estación</th><th>Llegada prevista</th><th>Mensaje</th><th>Estado</th></tr></thead><tbody id="renfe-alerts"></tbody></table></div></section>
  <section><h2>Salidas de hoy y próximas</h2><div class="table-wrap"><table><thead><tr><th>Operador</th><th>Ruta</th><th>Salida</th><th>Ocupación</th><th>Precio</th><th>Estado</th><th>Última lectura</th></tr></thead><tbody id="services"></tbody></table></div></section>
</main>
<script>
const $ = (selector) => document.querySelector(selector);
const fmt = (date) => date ? new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(date)) : '—';
const esc = (value) => String(value ?? '—').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const statusNames = {available:'Con plazas',full_or_unavailable:'Lleno / sin disponibilidad',schedule_only:'Solo horario',error:'Error',pending:'Pendiente',sent:'Enviado',failed:'Fallido',sending:'En curso',checked:'Comprobada'};
const statusColors = {available:'#46d7b0',full_or_unavailable:'#ff7b7b',schedule_only:'#ffc857',error:'#a8b7c9'};
function price(row){return row.ticket_price_cents==null?'—':(row.ticket_price_cents/100).toLocaleString('es-ES',{style:'currency',currency:row.ticket_currency||'EUR'})+(row.price_reference_date?' · ref. '+row.price_reference_date:'');}
function statusBadge(status){return '<span class="badge '+esc(status)+'">'+esc(statusNames[status]||status)+'</span>';}
function delayDuration(minutes){return minutes<0?minutes+' min':Math.floor(minutes/60)+' h '+String(minutes%60).padStart(2,'0')+' min';}
function occupancy(row){if(row.occupied_seats==null||!row.total_seats)return '—';return (row.occupied_seats/row.total_seats*100).toLocaleString('es-ES',{maximumFractionDigits:1})+'% ('+row.occupied_seats+'/'+row.total_seats+')';}
function dayLabels(end,count){const labels=[],d=new Date(end+'T12:00:00Z');for(let i=count-1;i>=0;i--){const x=new Date(d);x.setUTCDate(x.getUTCDate()-i);labels.push(x.toISOString().slice(0,10));}return labels;}
function setupCanvas(canvas){const width=Math.max(280,canvas.clientWidth||500),height=245,dpr=window.devicePixelRatio||1;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);return {ctx,width,height};}
function drawBars(canvas,labels,values,options){const color=options.color||'#46d7b0',percent=Boolean(options.percent),{ctx,width,height}=setupCanvas(canvas),left=40,right=8,top=14,bottom=38,plotH=height-top-bottom,plotW=width-left-right,max=percent?100:Math.max(1,...values);ctx.clearRect(0,0,width,height);ctx.font='11px system-ui';ctx.textBaseline='middle';ctx.strokeStyle='rgba(157,176,197,.18)';ctx.fillStyle='#9db0c5';for(let i=0;i<=4;i++){const y=top+plotH-(plotH*i/4);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(width-right,y);ctx.stroke();ctx.textAlign='right';ctx.fillText(percent?Math.round(max*i/4)+'%':String(Math.round(max*i/4)),left-7,y);}const slot=plotW/Math.max(1,labels.length),barW=Math.min(24,slot*.58);values.forEach((v,i)=>{const h=Math.max(v>0?2:0,plotH*v/max),x=left+slot*i+(slot-barW)/2,y=top+plotH-h;ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,barW,h,4);ctx.fill();ctx.fillStyle='#9db0c5';ctx.textAlign='center';ctx.fillText(labels[i].slice(8),left+slot*i+slot/2,height-16);});}
function drawStatus(data){const {ctx,width,height}=setupCanvas($('#status-chart')),rows=data.byStatus,colors=statusColors,total=rows.reduce((s,r)=>s+r.count,0),cx=Math.min(width*.34,145),cy=height*.5,r=Math.min(78,height*.36);ctx.clearRect(0,0,width,height);let angle=-Math.PI/2;rows.forEach(row=>{const span=total?row.count/total*Math.PI*2:0;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,angle,angle+span);ctx.closePath();ctx.fillStyle=colors[row.status]||'#79a9ff';ctx.fill();angle+=span;});ctx.beginPath();ctx.arc(cx,cy,r*.58,0,Math.PI*2);ctx.fillStyle='#101f32';ctx.fill();ctx.fillStyle='#e9f2fb';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='700 22px system-ui';ctx.fillText(String(total),cx,cy-4);ctx.font='11px system-ui';ctx.fillStyle='#9db0c5';ctx.fillText('expediciones',cx,cy+17);$('#status-legend').innerHTML=rows.map(row=>'<span class="legend-item"><i class="swatch" style="background:'+(colors[row.status]||'#79a9ff')+'"></i>'+esc(statusNames[row.status]||row.status)+': '+row.count+'</span>').join('')||'<span class="muted">Sin lecturas para hoy.</span>';}
let latestData;const routeSearch=$('#route-search'),operatorFilter=$('#operator-filter'),historySearch=$('#history-search'),historyStatus=$('#history-status');
function renderRoutes(){if(!latestData)return;const term=routeSearch.value.trim().toLocaleLowerCase('es'),operator=operatorFilter.value,routes=latestData.plannedRoutes.filter(r=>(!operator||r.operator===operator)&&(!term||[r.operator,r.origin,r.destination].join(' ').toLocaleLowerCase('es').includes(term)));$('#route-total').textContent=routes.length+' de '+latestData.plannedRoutes.length+' rutas';$('#planned-routes').innerHTML=routes.map(r=>'<tr><td>'+esc(r.operator)+'</td><td>'+esc(r.origin)+'</td><td>'+esc(r.destination)+'</td></tr>').join('')||'<tr><td colspan="3">No hay rutas que coincidan.</td></tr>';}
function renderHistory(){if(!latestData)return;const term=historySearch.value.trim().toLocaleLowerCase('es'),status=historyStatus.value,rows=latestData.history.filter(r=>(!status||r.status===status)&&(!term||[r.operator,r.origin,r.destination].join(' ').toLocaleLowerCase('es').includes(term)));$('#history-total').textContent=rows.length+' lecturas';$('#history-rows').innerHTML=rows.map(r=>'<tr><td>'+esc(r.service_date)+'</td><td>'+esc(r.operator)+'</td><td>'+esc(r.origin)+' → '+esc(r.destination)+'</td><td>'+esc(r.departure_time)+'</td><td>'+esc(occupancy(r))+'</td><td>'+esc(price(r))+'</td><td>'+statusBadge(r.status)+'</td><td>'+fmt(r.observed_at)+'</td></tr>').join('')||'<tr><td colspan="8">No hay lecturas con esos filtros.</td></tr>';}
routeSearch.addEventListener('input',renderRoutes);operatorFilter.addEventListener('change',renderRoutes);historySearch.addEventListener('input',renderHistory);historyStatus.addEventListener('change',renderHistory);
function render(data){const counts=Object.fromEntries(data.byStatus.map(x=>[x.status,x.count]));$('#updated').textContent='Hoy '+data.date+' · datos desde '+data.historyFrom+' · actualizado '+fmt(data.generatedAt);$('#history-range').textContent='Últimos 14 días · desde '+data.historyFrom;
const occupied=data.services.filter(x=>x.status==='available'&&x.occupied_seats!=null&&x.total_seats).length;$('#stats').innerHTML=[['Rutas planificadas',data.routeCount],['Expediciones hoy',data.services.length],['Con plazas verificadas',occupied],['Llenas / sin plazas',counts.full_or_unavailable||0],['Con precio',data.services.filter(x=>x.ticket_price_cents!=null).length],['Tweets enviados',data.sentTweets.length]].map(([k,v])=>'<div class="stat"><span>'+esc(k)+'</span><b>'+v+'</b></div>').join('');
const upcoming=data.services.filter(x=>x.dueAt&&new Date(x.dueAt).getTime()>Date.now()).sort((a,b)=>a.dueAt.localeCompare(b.dueAt)).slice(0,20);$('#upcoming').innerHTML=upcoming.map(x=>'<tr><td>'+esc(x.operator)+'</td><td>'+esc(x.origin)+' → '+esc(x.destination)+'</td><td>'+esc(x.service_date)+' '+esc(x.departure_time)+'</td><td>'+fmt(x.dueAt)+'</td><td>'+statusBadge(x.checked_at?'checked':'pending')+'</td></tr>').join('')||'<tr><td colspan="5">No hay comprobaciones pendientes próximas.</td></tr>';
const selected=operatorFilter.value,operators=[...new Set(data.plannedRoutes.map(r=>r.operator))];operatorFilter.innerHTML='<option value="">Todos los operadores</option>'+operators.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');operatorFilter.value=operators.includes(selected)?selected:'';latestData=data;renderRoutes();renderHistory();
const labels=dayLabels(data.date,14),sums=new Map();data.history.forEach(r=>{if(r.status==='available'&&r.occupied_seats!=null&&r.total_seats){const x=sums.get(r.service_date)||{sum:0,count:0};x.sum+=100*r.occupied_seats/r.total_seats;x.count++;sums.set(r.service_date,x);}});drawBars($('#occupancy-chart'),labels,labels.map(day=>{const x=sums.get(day);return x?x.sum/x.count:0;}),{percent:true});drawStatus(data);
const tweetsByDay=new Map();data.sentTweets.forEach(t=>{if(t.sent_at){const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t.sent_at));tweetsByDay.set(day,(tweetsByDay.get(day)||0)+1);}});drawBars($('#tweets-chart'),labels,labels.map(day=>tweetsByDay.get(day)||0),{color:'#79a9ff'});
$('#renfe-total').textContent=data.renfeTrains.length+' trenes en el inventario';$('#renfe-trains').innerHTML=data.renfeTrains.map(t=>'<tr><td>'+esc(t.commercial_code||t.circulation_code)+'</td><td>'+esc(t.circulation_code)+'</td><td>'+esc(t.corridor_code)+'</td><td>'+esc(t.next_station_code)+'</td><td>'+esc(t.next_station_arrival_estimate?.replace('T',' '))+'</td><td>'+delayDuration(t.delay_minutes)+'</td><td>'+fmt(t.last_seen_at)+'</td></tr>').join('')||'<tr><td colspan="7">Aún no hay lecturas de Renfe.</td></tr>';
$('#renfe-alerts').innerHTML=data.renfeAlerts.map(a=>'<tr><td>'+fmt(a.detected_at)+'</td><td>'+esc(a.commercial_code||a.circulation_code)+' · '+esc(a.corridor_code)+'</td><td>'+esc(a.next_station_code)+'</td><td>'+esc(a.expected_arrival_at.replace('T',' '))+'</td><td class="message-cell">'+esc(a.notification_text)+'</td><td>'+statusBadge(a.notification_status)+'</td></tr>').join('')||'<tr><td colspan="6">No hay avisos de llegadas nocturnas.</td></tr>';
$('#sent-tweets').innerHTML=data.sentTweets.map(t=>{const link=/^[0-9]+$/.test(t.post_id)?'<a class="tweet-link" href="https://x.com/i/web/status/'+encodeURIComponent(t.post_id)+'" target="_blank" rel="noopener noreferrer">Ver tweet ↗</a>':'—';return '<tr><td>'+fmt(t.sent_at)+'</td><td>'+t.event_count+'</td><td class="message-cell">'+esc(t.message)+'</td><td>'+link+'</td></tr>';}).join('')||'<tr><td colspan="4">Todavía no hay tweets enviados.</td></tr>';$('#tweet-total').textContent=data.sentTweets.length+' publicaciones';
$('#x-posts').innerHTML=data.xPosts.map(p=>'<tr><td>'+fmt(p.created_at)+'</td><td>'+esc(p.event_type==='bus_departure'?'Autobús':'Renfe')+'</td><td class="message-cell">'+esc(p.message)+'</td><td>'+statusBadge(p.status)+'</td><td>'+esc(p.error_message||'—')+'</td></tr>').join('')||'<tr><td colspan="5">La cola está vacía.</td></tr>';
$('#services').innerHTML=data.services.map(x=>'<tr><td>'+esc(x.operator)+'</td><td>'+esc(x.origin)+' → '+esc(x.destination)+'</td><td>'+esc(x.service_date)+' '+esc(x.departure_time)+'</td><td>'+esc(occupancy(x))+'</td><td>'+esc(price(x))+'</td><td>'+statusBadge(x.status)+'</td><td>'+fmt(x.observed_at)+'</td></tr>').join('')||'<tr><td colspan="7">Aún no hay lecturas.</td></tr>';}
async function refresh(){try{const response=await fetch('/api/dashboard',{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);render(await response.json());$('#load-error').style.display='none';}catch(error){$('#load-error').textContent='No se pudieron actualizar los datos. Se reintentará automáticamente.';$('#load-error').style.display='block';console.error(error);}}
refresh();setInterval(refresh,30000);window.addEventListener('resize',()=>{if(latestData)render(latestData);});
</script>`;
